project:
  type: website
  output-dir: docs

website:
  title: "Dash from Plotly"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog on Dash
      - href: https://dash.plotly.com/
        text: Official Tutorial
      - href: https://www.youtube.com/playlist?list=PLYD54mj9I2JevdabetHsJ3RLCeMyBNKYV
        text: Tutorial playlist
      - href: https://wasmdash.vercel.app/
        text: Wasmdash(for practice)

format:
  html:
    theme:
      light: [cerulean, styles.scss]
    highlight-style: a11y-dark
    mainfont: "Montserrat"
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
